### ISSUE TITLE
[時間錯誤] Jan 8 / ROS.Taipei: 淺談自動駕駛：從地表到太空

### ISSUE THREAD

**Issue by YuehChuan** [jserv/talks#1]
修正為Jan 7 / ROS.Taipei: 淺談自動駕駛：從地表到太空
<img width="489" alt="jsev-talk" src="https://user-images.githubusercontent.com/7314531/34346742-eb890194-ea35-11e7-9a9c-1fafc511759f.png">

**Comment by jserv** [comment]
Fixed. Thanks for reporting.
